package constants

import (
	"time"
)

//eth constants
const (
	CURRENCY_NOT_ENOUGH_ERR_MSG    = "insufficient funds for gas * price + value"
	ACCOUNT_AUTHENTICATION_ERR_MSG = "authentication needed: password or unlock"
	UNKNOWN_TRANSACTION_ERR_MSG    = "unknown transaction"

	TRANSACTION_STATUS_SUBMIT  = 0
	TRANSACTION_STATUS_SUCCESS = 1
	TRANSACTION_STATUS_FAIL    = 2
	TRANSACTION_STATUS_UNKNOWN = 3

	AMOUNT_ETH_TYPE = 1
	AMOUNT_PXC_TYPE = 2
)

const (
	PXCTOGOLD = 2
)

const (
	RECOMMEND_FOR_POOL = 0
	RECOMMEND_POOL     = 1
)

//pixie constants
const (
	PAPER_CIRCULATION_MAX = 5

	DEFAULT_NICKNAME_PREFIX = "P"

	RECOMMEND_TOPIC_PAGESIZE = 4
	RECOMMEND_ZONE_SIZE      = 18

	STYLE_MAX = 10000

	PIXIE_TRADE_STATUS_QUEUE   = 0
	PIXIE_TRADE_STATUS_SUCCESS = 1

	AUCTION_PRICE_LEGAL_GAP = 1.0 //百分比

	PIXIE_GOLD_TYPE = 1
	PIXIE_PXC_TYPE  = 2

	PIXIE_INIT_LAND_SIZE           = 7
	PIXIE_RECOMEMND_ITEM_PAGE_SIZE = 10

	PIXIE_LAND_MAX_SALE_SIZE              = 100
	PIXIE_RECOMMEND_POOL_BATCH_SIZE       = 100
	PIXIE_RECOMMEND_IN_COUNT_SIZE         = 17
	PIXIE_RECOMMEND_PAPER_DESIGN_GET_SIZE = 100
	PIXIE_PAPER_DESIGN_GET_SIZE           = 30
	PIXIE_OCCUPY_PAPERID_IN_SIZE          = 100

	PIXIE_DEFAULT_PAGE_SIZE = 20

	PIXIE_BUILD_DEFAULT_TIME = 120 //second

	PIXIE_CHECK_PAGE_SIZE = 1000

	PIXIE_RANDOM_VISIT_SIZE        = 2000
	PIXIE_REMOVE_RANDOM_VISIT_SIZE = 50

	PIXIE_VERIFY_DAY_LIMIT = 20
	VERIFY_TARGET          = 200

	VERIFY_REWARD_COUNT = 1000
	VERIFY_COPY_REWARD  = 1000

	COPY_REPORT_SUCCESS_LIMIT = 0.3

	PIXIE_RENT_MIN_LIMIT               = 1000
	PIXIE_RENT_CURRENCY_GOLD_MAX_LIMIT = 100000
	PIXIE_RENT_CURRENCY_PXC_MAX_LIMIT  = 100000

	PIXIE_PRICING_MIN_LIMIT               = 10
	PIXIE_PRICING_CURRENCY_GOLD_MAX_LIMIT = 10000
	PIXIE_PRICING_CURRENCY_PXC_MAX_LIMIT  = 100000

	PIXIE_AUCTION_MIN_LIMIT               = 100
	PIXIE_AUCTION_CURRENCY_GOLD_MAX_LIMIT = 100000
	PIXIE_AUCTION_CURRENCY_PXC_MAX_LIMIT  = 1000000

	// 套装
	PIXIE_SUIT_LIMIT    = 30
	PIXIE_CLOTHES_SPLIT = "-"

	PIXIE_GM_DEFAULT_PAGE_SIZE = 10
)

const (
	GET_SALE_INFO_KEY_ALL = "ALL"
)
const (
	PIXIE_SAVE_DB_ALL                   = "ALL"
	PIXIE_SAVE_DB_STATUS_SUIT_MAP       = "SUITMAP"
	PIXIE_SAVE_DB_STATUS_HOME_SHOW      = "HOMESHOW"
	PIXIE_SAVE_DB_STATUS_STREET_OPERATE = "STREET_OPERATE"
	PIXIE_SAVE_DB_STATUS_MAP_SKIN       = "MAP_ID"
	PIXIE_SAVE_DB_CURRENCY              = "CURRENCY"
)

var TagMap = map[string]string{
	"1":  "中国风",
	"2":  "欧式古典",
	"3":  "和风",
	"4":  "洛丽塔",
	"5":  "哥特风",
	"6":  "未来系",
	"7":  "童话风",
	"8":  "摇滚风",
	"9":  "森女",
	"10": "英伦",
	"11": "旗袍",
	"12": "婚纱",
	"13": "泳装",
	"14": "晚礼服",
	"15": "白领女郎",
	"16": "女仆装",
	"17": "军装",
	"18": "睡衣",
	"19": "泳装",
	"20": "居家服",
	"21": "黑暗",
	"22": "搞笑",
	"23": "另类",
	"24": "华丽",
}

const (
	GET_PAPER_DEFAULT_PAGE_SIZE = 48
	PAGE_TRADE_LOG_PAGE_SIZE    = 20
	PRODUCT_ONE_COLOTHES_TIME   = 600
)
const (
	TRADE_DEVIATION = 100000
)
const (
	RT_PARTY_DEFAULT_SUBJECT_SIZE = 3
	RT_PARTY_PLAYER_SIZE          = 5
	RT_PARTY_MATCH_TIMEOUT        = 180
	RT_PARTY_DEFAULT_TIMEOUT      = 3
	RT_PARTY_DEAD_TIME            = 1800
	RT_PARTY_RECONNECT_TIMEOUT    = 300

	RT_PARTY_CHAT_SIZE = 1000
	RT_PARTY_EXP       = 5

	RT_PARTY_SUBJECT_OFFER_TIME = 22
	RT_PARTY_SUBJECT_VOTE_TIME  = 17
	RT_PARTY_DRESS_TIME         = 240
	RT_PARTY_DRESS_VOTE_TIME    = 32

	RT_PARTY_SUBJECT_VOTE_CNT = 2
	RT_PARTY_DRESS_VOTE_CNT   = 2
)

const (
	GM_TABLE_NAME_PAPER        = "pixie_paper"
	GM_TABLE_NAME_OCCUPY       = "pixie_occupy"
	GM_TABLE_NAME_OCCUPY_LOG   = "pixie_occupy_log"
	GM_TABLE_NAME_PAPER_VERIFY = "pixie_paper_verify"
	GM_TABLE_NAME_TRADE        = "pixie_trade"
)

const (
	TIME_DOOR_EVENT_ID = -1
	MAX_LOG_SIZE       = 10240
	QINMI_FRIEND_MIN   = 60

	IAP_PLATFORM_APPLE  = "apple"
	IAP_PLATFORM_GOOGLE = "google"

	DEFAULT_HTTP_TIMEOUT = 30 //second
	KOR_PUSH_DAY_START   = 8
	KOR_PUSH_DAY_END     = 21
	// RECEIVE_PUSH_TAG       = "receive_push"
	// RECEIVE_NIGHT_PUSH_TAG = "receive_night_push"

	CURRENCY_CN  = "RMB"
	CURRENCY_KOR = "KRW"
	CURRENCY_US  = "USD"

	KOR_GAME_CODE           = 203000
	KOR_THIRD_CODE_KAKAO    = 7
	KOR_THIRD_CODE_FACEBOOK = 10
	KOR_OS_IOS_CODE         = 10
	KOR_OS_ANDROID_CODE     = 20
	KOR_STORE_ITUNES        = 1
	KOR_STORE_GOOGLE        = 5
)

const (
	GUILD_VICE_PRESIDENT_SIZE = 2

	DESIGN_MSG_UP_CLOTHES_TYPE          = 2
	DESIGN_MSG_SHOPCART_UP_CLOTHES_TYPE = 4
	DESIGN_MSG_DETAIL_SIZE              = 10

	DESIGNER_ZONE_CUSTOM_SIZE = 4

	AD_SETTLE_HOUR = 3

	SEARCH_DESIGNER_BATCH_SIZE = 8

	SHOP_CART_MAX_SIZE = 100

	GUILD_CONFIG_VICE_PRESIDENT_SET   = 1
	GUILD_CONFIG_VICE_PRESIDENT_UNSET = 0

	SEND_SOLD_DESIGNER_PUSH_KEY_PREFIX = "send_sold_designer_"
	ORDER_GAP                          = "_"
	THIRD_USERNAME_GAP                 = "-"
	CUSTOM_SHARE_DESIGNER_SIZE         = 2
	CUSTOM_SHARE_SIZE                  = 10
	GAME_SERVER_REPORT_STATUS_INTERVAL = 5 //seconds
	ELASTIC_NOT_FOUND_ERR_MSG          = "elastic: Error 404 (Not Found)"

	PARTY_FLOWER_MAX_CNT       = 50
	PRIZE_PARTY_FLOWER_MAX_CNT = 15
	CUSTOM_FILE_POSTFIX        = "file"
	KOR_LANGUAGE               = "korean"
	CLOTH_STAR_MULTI           = 50
	DESIGN_COIN_REWARD_COUNT   = 80

	PARTY_FLOWER_MAX = 10

	DAY_RT_PARTY_GOLD_LIMIT    = 10000
	DAY_RT_PARTY_DIAMOND_LIMIT = 25
	DAY_RT_PARTY_WIRE_LIMIT    = 10
	DAY_RT_PARTY_EXP_LIMIT     = 100

	CUSTOM_MAX_EXP = 42
)
const (
	INDEX     = 100
	RECOMMEND = 200
)
const (
	FORCLOTHESPOOL    = 1 //作品预选池
	CLOTHESPOOL       = 2 //作品池
	FORNEWCLOTHESPOOL = 3 //新人作品预选池
	NEWCLOTHESPOOL    = 4 //新人作品池

	FORDESIGNERPOOL    = 5 //设计师预选池
	DESIGNERPOOL       = 6 //设计师池
	FORNEWDESIGNERPOOL = 7 //新人设计师预选池
	NEWDESIGNERPOOL    = 8 //新人设计师池

	TOPICFORPOOL = 9  //专题预选池
	TOPICPOOL    = 10 //专题推荐池
)
const (
	XINYUE_MODEL = 103

	BUY_THEATER_DIAMOND  = 100
	DAY_THEATER_PLAY_CNT = 10

	MISSION_TILI = 4

	GUILD_WAR_CLAIM_START_HOUR    = 20
	GUILD_WAR_CLAIM_END_HOUR      = 22
	GUILD_WAR_SET_DEFEND_END_HOUR = 9

	GUILD_WAR_MEMBER_MIN = 25
	GUILD_WAR_MAX_MEDAL  = 30 * 3 * (12*7 - 1)

	GUILD_WAR_ATTACK_CNT = 2
	GUILD_WAR_MEDAL_CNT  = 3

	GUILD_WEEK_CLOTHES_SIZE    = 10
	GUILD_WEEK_PK_SUBJECT_SIZE = 15

	SHARE_REWARD_DIAMOND = 10

	GUILD_WAR_ATTEND_GOLD        = 2000
	GUILD_WAR_WIN_ONCE_GOLD      = 3000
	GUILD_WAR_ATTEND_ACTIVITY    = 20
	GUILD_WAR_WIN_REWARD_DIAMOND = 20

	GUILD_RANK_SIZE                = 5000
	GUILD_WAR_RANK_1_REWARD_DMD    = 8000
	GUILD_WAR_RANK_2_REWARD_DMD    = 4000
	GUILD_WAR_RANK_3_REWARD_DMD    = 2000
	GUILD_WAR_RANK_10_REWARD_DMD   = 1000
	GUILD_WAR_RANK_50_REWARD_DMD   = 500
	GUILD_WAR_RANK_100_REWARD_DMD  = 200
	GUILD_WAR_NEW_SEASON_MEDAL_MAX = 800

	GUILD_RANDOM_SIZE = 50

	GUILD_LOTTERY1_ACTIVITY = 3000
	GUILD_LOTTERY2_ACTIVITY = 8000
	GUILD_LOTTERY3_ACTIVITY = 13000
	GUILD_LOTTERY4_ACTIVITY = 18000

	GUILD_MEMBER_LOTTERY1_ACTIVITY = 50
	GUILD_MEMBER_LOTTERY2_ACTIVITY = 130
	GUILD_MEMBER_LOTTERY3_ACTIVITY = 210
	GUILD_MEMBER_LOTTERY4_ACTIVITY = 300

	GUILD_MISSION_ACTIVITY    = 5
	GUILD_PARTY_ACTIVITY      = 10
	GUILD_MARK_PARTY_ACTIVITY = 2
	GUILD_PK_ACTIVITY         = 15
	DAY_ACTIVITY_GOT_LIMIT    = 100

	CREATE_GUILD_DIAMOND     = 300
	GUILD_MAX_MEMBER         = 30
	GUILD_MAX_MEMBER_CLOTHES = 2

	RECORD_F_GOLD = 60
	RECORD_B_GOLD = 200
	RECORD_A_GOLD = 350
	RECORD_S_GOLD = 500

	FILE_SERVER_OSS    = "oss"
	FILE_SERVER_SIMPLE = "sfs"
	FILE_SERVER_FTP    = "ftp"

	KOR_LOGIN_TABLEHEAD  = "guid,uuid,cuid,gamecode,nickname,sex,age,levYn,userLv,authtoken,oscode,ostopverno,tempuserid,tokenredisDate,registdate,mappingdate"
	KOR_LOGIN1_TABLEHEAD = "logindate,logindateseq,cuid,isloginsuccessdiv,platformuserid,loginrootcode,gameCode,deviceid,platformcode,oscode,ostopverno"
	KOR_ORDER_TABLEHEAD  = "paylogid,eventdate,logtype,guid,platformuserid,platformcode,oscode,storetype,orderid,paydate,paytool,gamecode,gamename,itemname,currentcycode,amount,paycountry"

	DEFAULT_MAIL_EXPIRE_TIME = 14 * 24 * 3600 //seconds

	PK_START_DAY    = "20170102030000"
	GUILD_START_DAY = "20170102000000"
	GV_MEISHU_TOKEN = "MEISHU_PASSED"

	START_TILI  = 30
	V1_ADD_TILI = 5
	V2_ADD_TILI = 10
	V3_ADD_TILI = 15
	V4_ADD_TILI = 20
	V5_ADD_TILI = 25
	V6_ADD_TILI = 30
	V7_ADD_TILI = 35
	V8_ADD_TILI = 40
	V9_ADD_TILI = 45

	V1_BUY_DIAMOND = 100
	V2_BUY_DIAMOND = 300
	V3_BUY_DIAMOND = 500
	V4_BUY_DIAMOND = 1000
	V5_BUY_DIAMOND = 2000
	V6_BUY_DIAMOND = 5000
	V7_BUY_DIAMOND = 10000
	V8_BUY_DIAMOND = 20000
	V9_BUY_DIAMOND = 50000

	DESIGNER_LEVEL_2_POINT = 280
	DESIGNER_LEVEL_3_POINT = 1200
	DESIGNER_LEVEL_4_POINT = 3600
	DESIGNER_LEVEL_5_POINT = 7200
	DESIGNER_LEVEL_6_POINT = 14400

	GUILD_MEDAL_LEVEL_1_GOLD = 3000
	GUILD_MEDAL_LEVEL_2_GOLD = 6000
	GUILD_MEDAL_LEVEL_3_GOLD = 9000
	GUILD_MEDAL_LEVEL_4_GOLD = 12000
	GUILD_MEDAL_LEVEL_5_GOLD = 15000
	GUILD_MEDAL_LEVEL_6_GOLD = 20000

	GUILD_MEDAL_LEVEL_2 = 250
	GUILD_MEDAL_LEVEL_3 = 750
	GUILD_MEDAL_LEVEL_4 = 1750
	GUILD_MEDAL_LEVEL_5 = 3000
	GUILD_MEDAL_LEVEL_6 = 4500
)

const (
	MAIL_TYPE_XX_PARTY_RANK1           = 1
	MAIL_TYPE_XX_PARTY_RANK3           = 2
	MAIL_TYPE_CUSTOM_PASS              = 3
	MAIL_TYPE_GUILD_INOUT              = 4
	MAIL_TYPE_NOTIFY_GUILD_WAR         = 5
	MAIL_TYPE_SET_GUILD_VICE_PRESIDENT = 6
	MAIL_TYPE_AD_RETURN                = 7
	MAIL_TYPE_PXC_BUY_FAIL             = 8

	DESIGN_MSG_TYPE_PASS = 1
	DESIGN_MSG_TYPE_UP   = 2
	DESIGN_MSG_TYPE_DOWN = 3

	PUSH_STATUS_LINE = 1
	PUSH_STATUS_DONE = 2
)

const (
	PLATFORM_TEST            = "TEST"
	PLATFORM_IOS             = "IOS"
	PLATFORM_IOS_TEST        = "IOS_TEST"
	PLATFORM_ANDRIOD_TEST    = "ANDROID_TEST"
	PLATFORM_ANDRIOD_MAIN    = "ANDROID_MAIN"
	PLATFORM_ANDRIOD_UNION   = "ANDROID_UNION"
	PLATFORM_ANDRIOD_APP_BAO = "ANDROID_APP_BAO"

	ORDER_PLATFORM_PINGPP = "pingpp"

	CHANNEL_DEFAULT = "DEFAULT"

	COPY_STATUS_LINE = 0
	COPY_STATUS_DONE = 1

	BUY_PARTY_GOLD         = 2000
	JOIN_PARTY_REWARD_GOLD = 1000
	CASUAL_PARTY_1_GOLD    = 10000
	CASUAL_PARTY_2_GOLD    = 8000
	CASUAL_PARTY_3_GOLD    = 5000
	CASUAL_PARTY_20_GOLD   = 2000
)

const (
	ONE_CODE_TYPE = 1
	MULTI_TYPE    = 2
	SINGLE_TYPE   = 3

	REG_KEFU_PACK_ID    = -2
	REG_YUNYING_PACK_ID = -3

	ORIGIN_OFFICIAL = 0
	ORIGIN_DESIGNER = 1

	GOLD_TYPE        = 1
	DIAMOND_TYPE     = 2
	DESIGN_COIN_TYPE = 3
	PXC_TYPE         = 4

	CLO_LEN = 19

	F_RECORD_EXP   = 2
	RECORD_EXP     = 5
	PARTY_EXP      = 20
	PK_WIN_EXP     = 12
	PK_LOSE_EXP    = 8
	MARK_PARTY_EXP = 4

	HOPE_STATUS_SENDED    = 1
	HOPE_STATUS_DONE      = 2
	HOPE_STATUS_DONE_READ = 3
	HOPE_STATUS_CLEAN     = 4

	COPY_REPORT_TYPE = 0
	COPY_SHENSU_TYPE = 1

	DEFAULT_PARTY_ITEM_POPU = 100
	DESIGN_MSG_REDIS_SIZE   = 1000

	DEFAULT_DEL_USER_DURATION = 7 //days
)

const (
	NOTICE_KEY_PREFIX           = "notice_"    //contain notice info
	NOTICE_SET_PREFIX           = "notice_to_" //contains notice id
	NOTICE_ID_ADD_FRIEND_PREFIX = "af_"

	NEW_FRIEND_SET_PREFIX = "new_friend_to_" //contains new friend info
	NEW_PIECE_SET_PREFIX  = "new_piece_to_"  //contains new clo piece info

	NOTICE_TYPE_ADD_FRIEND                 = 1
	NOTICE_TYPE_SWAP_CLOTHES_PIECE         = 2
	NOTICE_TYPE_SWAP_CLOTHES_PIECE_RESP    = 3
	NOTICE_TYPE_ADD_FRIEND_RESPONSE        = 4
	NOTICE_TYPE_SWAP_CLOTHES_PIECE_TIMEOUT = 5
	NOTICE_TYPE_REJECT_SWAP_CLO_PIECE      = 6

	STAGE_CZ = "CZ"
	STAGE_GZ = "GZ"
	STAGE_DX = "DX"
	STAGE_SH = "SH"
	STAGE_5P = "5P"
)

const (
	MAIL_ERR_SUBJECT      = "妖精的衣橱-服务端异常"
	MAIL_CRON_ERR_SUBJECT = "妖精的衣橱-服务端定时任务异常"
)

const (
	MONTH_CARD_REWARD_TYPE_SUIT = 1

	HEARTBEAT_GAP = 60

	PARTY_CASUAL_TYPE  = 0
	PARTY_PRIZE_TYPE   = 1
	PARTY_COSPLAY_TYPE = 2
	PARTY_FORBID_TYPE  = 3

	DAY_BUY_TILI_LIMIT = 3

	CASUAL_PARTY_HOUR_SIZE = 5
	PARTY_PLAYER_MAX_SIZE  = 10000

	CASUAL_PARTY_JOIN_RECOVER_INTERVAL = 3600 //1 HOUR = 1 JOIN CNT
	MARK_PARTY_RECOVER_INTERVAL        = 300  //5 MIN = 1 MARK CNT

	RT_PARTY_CHAT_EXPIRE_SECOND    = 24 * 3600
	RT_PARTY_DEFAULT_EXPIRE_SECOND = 3 * 24 * 3600
	COSPLAY_LAST_SECOND            = 32 * 24 * 3600

	FRIEND_PARTY_EXPIRE = 60

	CASUAL_PARTY_JOIN_MAX_CNT = 5
	MARK_PARTY_MAX_CNT        = 50

	UPLOAD_CUSTOM_DAY_LIMIT = 10
	UPLOAD_HELP_DAY_LIMIT   = 20

	FRIENDS_MAX_SIZE = 200

	MSG_BOARD_SIZE_LIMIT = 100

	SHOP_CART_PUSH_BATCH_SIZE = 1000

	PK_RANK_SIZE  = 10000
	PK_GRANK_SIZE = 10000

	PUSH_TYPE_GUILD_WAR      = 1
	PUSH_TYPE_GUILD          = 2
	PUSH_TYPE_FRIEND_REQUEST = 3
	PUSH_TYPE_HOPE_DONE      = 4
	PUSH_TYPE_PARTY_INVITE   = 5
	PUSH_TYPE_CUSTOM_NEW     = 6
	PUSH_TYPE_SHOP_CART      = 7
)

const (
	SHIKONGZHIMEN                    = "shi_kongzhimen"
	KOR_SHIKONGZHIMEN_PARAMS         = "kor_shikongzhimen"
	SPECIAL_MISSION_KEY              = "special_mission"
	BLOCK_LIST_KEY                   = "block_list"
	MAINTAIN_STATUS_KEY              = "is_maintain"
	GAME_PARAM_KEY                   = "game_param"
	MAINTAIN_WHITE_LIST_KEY          = "maintain_white_list"
	BLACK_GAME_SERVER_LIST_KEY       = "black_game_server_list"
	BLACK_ACCOUNT_LIST_KEY           = "black_account_list"
	ALLOW_PATCH_CONFIG_KEY           = "allow_patch"
	CHANNEL_LIMIT_KEY                = "channel_limit"
	DESIGN_COIN_KEY                  = "design_coin"
	LAST_REFRESH_PK_RANK_TIME_KEY    = "last_refresh_pk_rank_time"
	COPY_CUSTOM_KEY                  = "copy_custom_key"
	DEL_USER_DURATION_KEY            = "del_user_duration"
	ERR_MAIL_RECEIVER_LIST_KEY       = "err_mail_receiver_list"
	CHANNEL_SHARE_URL_KEY_PREFIX     = "channel_share_url_"
	CHANNEL_FORBID_LIST_KEY          = "channel_forbid_list"
	DESIGNER_BAN_MAP_KEY             = "designer_ban_map"
	CUSTOM_REPLACE_MAP_KEY           = "custom_replace_map"
	HOT_DESIGNER_LIST_KEY            = "hot_designer_list"
	SALE_RANK_CHANGE_DESIGN_COIN_KEY = "sale_rank_change_design_coin"
	MONTH_CARD_REWARD_KEY            = "month_card_reward"
	RT_PARTY_DEFAULT_SUBJECT_KEY     = "rt_party_default_subject_map"
	PRIZE_PARTY_CLOSE_KEY            = "prize_party_close"
	LOG_UPLOAD_PLAYER_LIST_KEY       = "log_upload_player_list"

	TEMP_SALE_EVENT_START_TIME_KEY        = "temp_sale_event_start_time"
	TEMP_SALE_EVENT_END_TIME_KEY          = "temp_sale_event_end_time"
	TEMP_SALE_EVENT_UPLOAD_BEGIN_TIME_KEY = "temp_sale_upload_begin_time"
)

const (
	LOCK_KEY_RECOVER_COS_COMMENTS_PREFIX = "recover_cos_comments_"
)
const (
	DATALOG_LEN = 10240
)
const (
	SPECIAL_EVENT_KEY_PREFIX = "se_"
	STAMP_EVENT_TOKEN        = "_stamp"

	GLOBAL_USER_HASH_KEY_PREFIX                 = "guh_"
	GLOBAL_USER_HASH_KEY_NICKNAME_VALUE         = "nickname"
	GLOBAL_USER_HASH_KEY_DESIGNER_POINTS_VALUE  = "points"
	GLOBAL_USER_HASH_KEY_DESIGNER_DIAMOND_VALUE = "diamond"
	GLOBAL_USER_HASH_KEY_DESIGNER_GLOD_VALUE    = "gold"
	GLOBAL_USER_HASH_KEY_DESIGNER_COIN_VALUE    = "coin"

	GLOBAL_USER_HASH_KEY_DESIGNER_TOTAL_COUNT_VALUE  = "total_count"
	GLOBAL_USER_HASH_KEY_DESIGNER_PASSED_COUNT_VALUE = "passed_count"
	GLOBAL_USER_HASH_KEY_DESIGNER_FENSI_COUNT_VALUE  = "fensi_count"
	GLOBAL_USER_HASH_KEY_DESIGNER_DESC_VALUE         = "desc"
	GLOBAL_USER_HASH_KEY_DESIGNER_ETH_ACCOUNT_VALUE  = "eth_account"

	DESIGNER_PASSED_COUNT_SET  = "gf_designer_passed"
	DESIGNER_TOTAL_DIAMOND_SET = "gf_designer_total_diamond"
	DESIGNER_TOTAL_GOLD_SET    = "gf_designer_total_gold"
	DESIGNER_TOTAL_SALE_SET    = "gf_designer_total_sale"

	DESIGNER_PASSED_MONTH_KEY_PREFIX        = "dpm_"
	DESIGNER_PASSED_EXP_MONTH_KEY_PREFIX    = "dpem_"
	DESIGNER_TOTAL_DIAMOND_MONTH_KEY_PREFIX = "dtdm_"
	DESIGNER_TOTAL_GOLD_MONTH_KEY_PREFIX    = "dtgm_"
	DESIGNER_TOTAL_COIN_MONTH_KEY_PREFIX    = "dtcm_"

	DESIGNER_TOTAL_SALE_MONTH_KEY_PREFIX = "dtsm_"

	THEATER_RANK_KEY_PREFIX = "trkp_"

	//redis keys
	COS_ITEM_LIST_TIME_KEY_PREFIX  = "gcit_" //list order by time
	COS_ITEM_LIST_SCORE_KEY_PREFIX = "gcis_" //sorted set order by total score
	COS_ITEM_USER_KEY_PREFIX       = "gciu_" //list contains user upload items
	COS_ITEM_ID_SET_PREFIX         = "gcii_" //sorted set order by item id
	COS_ITEM_SELF_KEY_PREFIX       = "gciskp_"

	DAY_NEW_CUSTOM_LIST_KEY_PREFIX = "dnclkp_"

	COS_ITEM_LIST_TOP_KEY_PREFIX       = "gcitp_" //top item list
	COS_TOP_ITEM_KEY_PREFIX            = "gcitfc_"
	COS_ITEM_USER_MARK_LIST_KEY_PREFIX = "gcium_" //item list user append marks
	COSPLAY_TYPE_LIST_KEY              = "gclt_"
	COS_ITEM_CMT_KEY_PREFIX            = "gcic_" //cos item comment list
	COS_ITEM_HAS_CMT_KEY_PREFIX        = "gcihc_"
	NOTICE_EXIST_KEY_PREFIX            = "gne_"
	MAIL_EXIST_KEY_PREFIX              = "gme_"
	CUSTOM_INFO_KEY_PREFIX             = "gci_"

	TEMP_SALE_RANK_KEY_PREFIX = "tsrk_"

	SINGLE_PUSH_JOB_LIST_KEY = "spjlk"

	// CUSTOM_PASSED_LIST_KEY             = "gcpl"
	GLOBAL_USER_SET_KEY     = "gusk"
	DESIGNER_NEW_KEY_PREFIX = "dn_"

	CUSTOM_PROCESSING_ID_KEY = "cpik"

	GUILD_NEWEST_BOARD_ID_KEY_PREFIX = "gnbikp_"

	DAY_ORDER_CNT_KEY_PREFIX         = "docp_"
	DAY_ORDER_AMOUNT_KEY_PREFIX      = "doap_"
	DAY_NEW_PLAYER_CNT_KEY_PREFIX    = "dnpcp_"
	DAY_ACTIVE_PLAYER_SET_KEY_PREFIX = "dapsp_"

	PARTY_LIST_KEY_PREFIX                 = "gp_"
	PARTY_SELF_KEY_PREFIX                 = "gps_"
	PARTY_ITEM_LIST_KEY_PREFIX            = "gpil_"
	PARTY_ITEM_SELF_KEY_PREFIX            = "gpi_"
	PARTY_ITEM_RANK_LIST_KEY_PREFIX       = "gpirl_"
	PARTY_ITEM_RANK_LIST_CACHE_KEY_PREFIX = "gpirlc_"
	PARTY_ITEM_FLOWER_SET_PREFIX          = "gpifs_"
	PARTY_ITEM_CMT_LIST_PREFIX            = "gpicl_"
	PARTY_ITEM_GLOBAL_SET                 = "gpigs"
	PARTY_FRIEND_JOIN_CACHE_KEY_PREFIX    = "pfjc_"
	PARTY_FRIEND_HOST_CACHE_KEY_PREFIX    = "pfhc_"
	PARTY_PRIZE_PLAYER_RANK_CACHE_KEY     = "ppprc"
	PARTY_PRIZE_POOL_RANK_CACHE_KEY       = "ppplrc"
	PARTY_INVITE_FLOWER_KEY_PREFIX        = "pif_"
	PARTY_INVITE_ATTEND_KEY_PREFIX        = "pia_"
	PARTY_CNT_KEY_PREFIX                  = "pc_"
	PARTY_CASUAL_GLOBAL_LIST              = "pcgl"
	PARTY_PRIZE_GLOBAL_LIST               = "ppgl"
	PARTY_INVITE_LIST_KEY_PREFIX          = "pinl_"
	PARTY_GLOBAL_INVITE_SET_KEY           = "pgis"
	PARTY_COSPLAY_GLOBAL_LIST             = "pcosgl"

	GUILD_GWEEK_MEDAL_RANK_SET_KEY_PREFIX     = "ggrs_"
	GUILD_GWEEK_MEDAL_RANK_CACHE_KEY_PREFIX   = "ggmrc_"
	GUILD_WEEK_ACTIVITY_RANK_SET_KEY_PREFIX   = "gwars_"
	GUILD_WEEK_ACTIVITY_RANK_CACHE_KEY_PREFIX = "gwarc_"

	USER_KEY_PREFIX              = "gu_"
	MAIL_SET_PREFIX              = "mst_"
	HELP_LIST_KEY                = "ghl"
	HELP_KEY_PREFIX              = "gh_"
	HELP_COMMENT_LIST_KEY_PREFIX = "ghc_"
	HELP_CMT_CNT_KEY_PREFIX      = "ghcc_"
	HELP_HAS_CMT_KEY_PREFIX      = "ghhc_"
	// USER_CLO_PIECE_KEY_PREFIX    = "gucp_"
	CUSTOM_USER_LIST_KEY_PREFIX = "gcul_"
	GLOBAL_KEY                  = "gg_"
	GF_PK_LIST_KEY_PREFIX       = "gpl_"
	PK_WEEK_RANK_KEY_PREFIX     = "gpwr_"
	PK_GWEEK_RANK_KEY_PREFIX    = "gpgwr_"

	GUILD_APPLY_LIST_KEY_PREFIX    = "gal_"
	GUILD_NEW_APPLY_CNT_KEY_PREFIX = "gnac_"

	BOARD_NEW_SIGN_KEY_PREFIX  = "bns_"
	BOARD_FISR_PAGE_KEY_PREFIX = "bfp_"

	GLOBAL_DESIGN_MSG_LIST_KEY     = "gdml"
	NEW_GLOBAL_DESIGN_MSG_LIST_KEY = "ngdml"
	DESIGN_MSG_CNT_KEY_PREFIX      = "dmck_"

	//rt party
	RT_PARTY_HOST_LIST_KEY_PREFIX   = "rphl_"
	RT_PARTY_HOST_KEY_PREFIX        = "rphk_"
	RT_PARTY_HOST_JOINER_KEY_PREFIX = "rphjk_"
	// RT_PARTY_JOINER_DRESS_KEY_PREFIX     = "rpjdk_"
	// RT_PARTY_JOINER_SYNC_TIME_KEY_PREFIX = "rpstk_"
	RT_PARTY_JOINER_HASH_KEY_PREFIX = "rpjhk_"
	RT_PARTY_CHAT_LIST_KEY_PREFIX   = "rpclk_"

	ORDER_HASH_PREFIX = "go_"

	CHANNEL_NEW_PLAYER_CNT_KEY_PREFIX     = "cnpck_"
	ALL_CHANNEL_NEW_PLAYER_CNT_KEY_PREFIX = "acnpck_"
	ACTIVATION_CODE_GAME1                 = "game1Code"
	ACTIVATION_CODE_GAME2                 = "game2Code"
	ACTIVATION_CODE_GAME3                 = "game3Code"
	CHANNEL_NEW_ORDER_CNT_KEY_PREFIX      = "cnock_"
	ALL_CHANNEL_NEW_ORDER_CNT_KEY_PREFIX  = "acnock_"

	CHANNEL_NEW_ORDER_AMOUNT_KEY_PREFIX     = "cnoak_"
	ALL_CHANNEL_NEW_ORDER_AMOUNT_KEY_PREFIX = "acnoak_"

	GLOBAL_HOT_DESIGNER_RESP_KEY = "ghdrk"

	COS_ITEM_CMT_LIST_SIZE = 50
	TOP_COS_EXPIRE_TIME    = 900
	MAIL_EXPIRE_TIME       = 1200
	USER_EXPIRE_TIME       = 900
	DEFAULT_EXPIRE_TIME    = 900
	// DEFAULT_CUSTOM_EXPIRE_TIME = 3600
	HELP_CMT_CNT_KEY_EXPIRE = 900
	HELP_CMT_EXPIRE_TIME    = 900
	BOARD_PAGE_SIZE         = 10

	MONEY_TYPE_GOLD            = "GOLD"
	MONEY_TYPE_DIAM            = "DIAM"
	DAY_CONTRIBUTION_TEST      = 3600
	DAY_CONTRIBUTION_EXP       = 43200
	DAY_REWARD_EXP             = 86400
	WEEKEND_CONTRIBUTION_EXP   = 604800
	CONTRIBUTION_MAX           = 100
	CONTRIBUTION_DETAILONE_MAX = 99
	CONTRIBUTION_TOP           = 0

	DIAMOND_PREFIX = 320
	GOLD_PREFIX    = 1
	PXC_PREFIX     = 160

	MONTH28_CONTRIBUTION_EXP = 2419200
	MONTH29_CONTRIBUTION_EXP = 2505600
	MONTH30_CONTRIBUTION_EXP = 2592000
	MONTH31_CONTRIBUTION_EXP = 2678400

	JOIN_ADVERISING_PRICE = 200

	MAIL_MAX_SIZE      = 1000
	HELP_LIST_SIZE     = 100
	HELP_CMT_LIST_SIZE = 50
	COSPLAY_LIST_SIZE  = 50
	GF_PK_MAX_SIZE     = 5000

	DEFAULT_REPORT_DS = 93

	SP_REPORT_NAME         = "SP"
	DAU_REPORT_NAME        = "DAU"
	COS_REPORT_NAME        = "COS_REPORT"
	PARTY_REPORT_NAME      = "PARTY_REPORT"
	PK_REPORT_NAME         = "PK_REPORT"
	MAGIC_CASH_REPORT_NAME = "MAGIC_CASH_REPORT"
	DESIGNER_REPORT_NAME   = "DESIGNER_REPORT"
	COMBINE_REPORT_NAME    = "COMBINE_REPORT"
	PIECE_REPORT_NAME      = "PIECE_REPORT"
	XIAOJU_REPORT_NAME     = "XIAOJU_REPORT"
	YINDAO_REPORT_NAME     = "YINDAO_REPORT"
	MISSION_REPORT_NAME    = "MISSION_REPORT"
	ADVERISINGLIST         = "ADVERISING_LIST"

	SWAP_CLO_PIECE_COUNT_DAY_LIMIT = 4
	SWAP_CLO_PIECE_NUM_LIMIT       = 4

	SUIT_LIMIT = 10

	EVENT_TILI_REWARD_KEY = "DEFAULT"

	PK_ESCAPE_POINT = -1
	XX_PK_WIN_POINT = 1
	JJ_PK_WIN_POINT = 2
	PK_LOSE_POINT   = -1
)
const (
	AD_CONFIG_REWARD_DAY   = 1
	AD_CONFIG_REWARD_MONTH = 2
)

const (
	ADVERTISING_DAY_CONTRIBUTION   = "day"
	ADVERTISING_MONTH_CONTRIBUTION = "month"
	ADVERTISING_ALL_CONTRIBUTION   = "all"
	AD_AUCTION_GOLD                = 1000
	AD_AUCTION_DIAM                = 100
	AD_REWARD_ONE                  = 3
	AD_REWARD_TEN                  = 10
	AD_REWARD_THIRTY               = 30
)

const (
	LOGIN_FOR_GAME_SERVER_TYPE         = 2
	GAME_LOCAL_FOR_GM_SERVER_TYPE      = 3
	LOGIN_FOR_LOCAL_SERVER_TYPE        = 4
	GAME_GLOBAL_FOR_PLAYER_SERVER_TYPE = 5

	HEARTBEAT_TIME               = 60 //second
	TIME_OUT       time.Duration = 30
)

const (
	FILE_NOT_EXIST_MSG    = "no such file or directory"
	SQL_NO_DATA_ERR_MSG   = "sql: no rows in result set"
	RDS_NO_DATA_ERR_MSG   = "redigo: nil returned"
	PIECE_NOT_ENOUGH_MSG  = "not enough piece"
	PLAYER_BAN_MSG        = "player banned"
	PLAYER_DELETING_MSG   = "player deleting"
	PLAYER_DELED_MSG      = "player deled"
	PLAYER_LIMITED_MSG    = "player channel limited"
	SQL_DUPLICATE_KEY_MSG = "Duplicate entry"
	LOTTERY_ERR_CODE      = "lottery failed "
	REDIS_GET_PARAMS_ERR  = "redis get params err"
)

const (
	SERVER_TYPE_GM                     = "GM"
	SERVER_TYPE_GV                     = "GV"
	SERVER_TYPE_GL                     = "GL"
	SERVER_TYPE_GL_TS                  = "GL_TS"
	SERVER_TYPE_GMLOG                  = "GMLOG"
	SERVER_TYPE_GMLOG_MANUAL           = "GMLOG_MANUAL"
	SERVER_TYPE_GENLOG                 = "GENLOG"
	SERVER_TYPE_CHECK_CLO              = "CHECK_CLO"
	SERVER_TYPE_SNAPSHOT_PLAYER        = "SNAPSHOT_PLAYER"
	SERVER_TYPE_SIMPLE_REPORT          = "SIMPLE_REPORT"
	SERVER_TYPE_SIMPLE_REPORT_INIT     = "SIMPLE_REPORT_INIT"
	SERVER_TYPE_SIMPLE_REPORT_MANUAL   = "SIMPLE_REPORT_MANUAL"
	SERVER_TYPE_GEN_ORDER              = "GEN_ORDER"
	SERVER_TYPE_PERF                   = "PERF"
	SERVER_TYPE_S_FILE_SERVER          = "S_FILE_SERVER"
	SERVER_TYPE_REVOKE_CLOTHES         = "REVOKE_CLOTHES"
	SERVER_TYPE_SIMPLE_TEST            = "SIMPLE_TEST"
	SERVER_TYPE_SETTLE_DESIGNER_REWARD = "SETTLE_DESIGNER_REWARD"
	SERVER_TYPE_SEND_DESIGNER_RANK     = "SEND_DESIGNER_RANK"
)

// FTP存储路径配置
const (
	DefaultPath    = `/tmp/GMKorlog/`
	DefaultFTPPath = `/`
)
const (
	C1_PLAYER = "PLAYER"
	C1_ITEM   = "ITEM"
	C1_SYSTEM = "SYSTEM"
)

const (
	C2_ANNORMAL = "ABNORMAL"

	//C1_PLAYER
	C2_LOGIN_SNAPSHOT = "LOGIN_SNAPSHOT"
	C2_LOGIN          = "LOGIN"
	C2_PAY            = "PAY"
	C2_DIAMOND        = "DIAMOND"
	C2_MONEY          = "MONEY"
	C2_PXC            = "PXC"
	C2_DESIGN_COIN    = "DESIGNCOIN"
	C2_TILI           = "TILI"
	C2_VIP            = "VIP"
	C2_CLO_PIECE      = "CLO_PIECE"
	C2_FRIEND         = "FRIEND"
	C2_CLO_PIECE_SWAP = "CLO_PIECE_SWAP"
	C2_BG             = "BACKGROUND"

	C2_VIP_EXP = "VIP_EXP"

	C2_CUSTOM_PASS       = "CUSTOM_PASS"
	C2_CUSTOM_REJECT     = "CUSTOM_REJECT"
	C2_CUSTOM_PROCESSING = "CUSTOM_PROCESSING"
	C2_DEL_CLOTHES       = "DEL_CLOTHES"

	C2_MAIL = "MAIL"

	//C1_ITEM
	C2_NITEM   = "NITEM"
	C2_CLOTHES = "CLOTHES"

	//C1_SYSTEM
	C2_DESIGNER = "DESIGNER"

	C2_COSPLAY = "COSPLAY"

	C2_LOTTERY = "LOTTERY"
	C2_MISSION = "MISSION"

	C2_PK = "PK"

	C2_HELP = "HELP"

	C2_PROFILE    = "PROFILE"
	C2_CLIENT_LOG = "CLIENT_LOG"

	C2_MAGIC      = "MAGIC"
	C2_MAGIC_CASH = "MAGIC_CASH"
	C2_GM         = "GM"
	C2_GV         = "GV"

	C2_TAILOR = "TAILOR"

	C2_CMT_PARTY_ITEM     = "CMT_PARTY_ITEM"
	C2_MARK_PARTY_ITEM    = "MARK_PARTY_ITEM"
	C2_BE_MARK_PARTY_ITEM = "BE_MARK_PARTY_ITEM"

	C2_JOIN_PARTY_CNT = "JOIN_PARTY_CNT"
	C2_MARK_PARTY_CNT = "MARK_PARTY_CNT"

	C2_PARTY  = "PARTY"
	C2_FLOWER = "FLOWER"
	C2_CUSTOM = "CUSTOM"

	C2_GIFT = "GIFT"

	C2_EXP       = "EXP"
	C2_JUHUA     = "JUHUA"
	C2_JUHUA_CHA = "JUHUA_CHA"

	C2_HOPE = "HOPE"

	C2_QINMI = "QINMI"

	C2_NEW = "NEW"

	C2_ORDER          = "ORDER"
	C2_KOR_UNREGISTER = "KOR_UNREGISTER"

	C2_CLOTH  = "CLOTH"
	C2_ITEM1  = "ITEM1"
	C2_WIRE   = "WIRE"
	C2_NEEDLE = "NEEDLE"

	C2_UPLOAD_PAPER = "UPLOAD_PAPER"

	C2_DESIGNER_FOLLOW = "DESIGNER_FOLLOW"
	C2_ONLINE          = "ONLINE"
	C2_GUILD           = "GUILD"
	C2_SHARE_CLICK     = "SHARE_CLICK"
)
const (
	ITEM_TYPE_ENTRANCE  = "COSPLAY entrance"
	ITEM_TYPE_SPEAK     = "COSPLAY speak"
	ITEM_TYPE_SPEED     = "COSPLAY speed"
	ITEM_TYPE_RIGHT     = "COSPLAY speak right"
	ITEM_TYPE_SPEEDER   = "COSPLAY speeder"
	ITEM_TYPE_INTER_CUT = "COSPLAY inter-cut"
)
const (
	C3_DEFAULT        = "DEFAULT"
	C3_LOGIN_LOG_KOR  = "LOGIN_LOG_KOR"
	C3_LOGIN1_LOG_KOR = "LOGIN_LOG1_KOR"
	C3_ORDER_LOG_KOR  = "C3_ORDER_LOG_KOR"
	C3_KOR_CODE1      = "GAMECODE1"
	C3_KOR_CODE2      = "GAMECODE2"
	C3_KOR_CODE3      = "GAMECODE3"

	C3_RECLAIM = "RECLAIM"

	C3_DEL_MAIL            = "DEL_MAIL"
	C3_RECEIVE_MAIL        = "RECEIVE_MAIL"
	C3_TAIlOR_DECO_CLOTHES = "TAIlOR_DECO_CLOTHES"

	C3_BG_BUY               = "BUY_BG"
	C3_CREATE_GUILD         = "CREATE_GUILD"
	C3_APPLY_GUILD          = "APPLY_GUILD"
	C3_CONFIG_GUILD         = "CONFIG_GUILD"
	C3_QUIT_GUILD           = "QUIT_GUILD"
	C3_KICK_MEMBER          = "KICK_MEMBER"
	C3_DISBAND_GUILD        = "DISBAND_GUILD"
	C3_TRANSFER_GUILD       = "TRANSFER_GUILD"
	C3_PASS_APPLY           = "PASS_APPLY"
	C3_REJECT_APPLY         = "REJECT_APPLY"
	C3_GUILD_LOTTERY        = "GUILD_LOTTERY"
	C3_ATTACK_OPPONENT      = "ATTACK_OPPONENT"
	C3_SET_DEFEND           = "SET_DEFEND"
	C3_MATCH_WAR            = "MATCH_WAR"
	C3_OFFER_GUILD_CLOTHES  = "OFFER_GUILD_CLOTHES"
	C3_CANCEL_GUILD_CLOTHES = "CANCEL_GUILD_CLOTHES"
	C3_DEL_GUILD            = "GUILD"
	C3_LEAVE_A_MESSAGE      = "LEAVE_A_MESSAGE"
	C3_SEND_FLOWER          = "SEND_FLOWER"
	//plot mission
	C3_MISSION = "MISSION"

	//daily task & accomplishment
	C3_TASK = "TASK"

	C3_SYSTEM_RECOVER = "SYSTEM_RECOVER"

	C3_DIAMOND_CONSUME = "DIAMOND_CONSUME"

	C3_ITEM_PREFIX  = "ITEM_"
	C3_UNLOCK_LEVEL = "UNLOCK_LEVEL"
	C3_S_SUIT       = "S_SUIT"
	C3_TAG          = "TAG"

	C3_PK = "PK"

	C3_LINE       = "LINE"
	C3_PROCESSING = "PROCESSING"
	C3_PASSED     = "PASSED"
	C3_REJECT     = "REJECT"

	C3_GET_MAIL_GIFT = "GET_MAIL_GIFT"

	C3_SUCCESS = "SUCCESS"
	C3_FAIL    = "FAIL"

	C3_COS_ITEM_UPLOAD = "COS_ITEM_UPLOAD"
	C3_COS_COMMENT     = "COS_COMMENT"
	C3_COS_ITEM_SCORE  = "COS_ITEM_SCORE"

	C3_GOLD           = "GOLD"
	C3_DIAMOND        = "DIAMOND"
	C3_REPLAY_MISSION = "REPLAY_MISSION"

	C3_SKIP_PLOT = "SKIP_PLOT"

	C3_DESIGNER_UPLOAD = "DESIGNER_UPLOAD"
	C3_DESIGNER_CANCEL = "DESIGNER_CANCEL"
	C3_DESIGNER_SELL   = "DESIGNER_SELL"
	C3_DESIGNER_PASS   = "PASS"
	C3_DESIGNER_REJECT = "REJECT"
	C3_DESIGNER_INFO   = "DESIGNER_INFO"

	C3_HELP          = "HELP"
	C3_HELP_CMT      = "HELP_CMT"
	C3_HELP_FOLLOW   = "HELP_FOLLOW"
	C3_HELP_UNFOLLOW = "HELP_UNFOLLOW"

	C3_API_COST = "API_COST"

	C3_ADD_FRIEND    = "ADD_FRIEND"
	C3_REMOVE_FRIEND = "REMOVE_FRIEND"

	C3_UPLOAD_CLOTHES = "UPLOAD_CLOTHES"
	//clo piece swap
	C3_SEND      = "SEND"
	C3_AGREE     = "AGREE"
	C3_HELP_HOPE = "HELP_HOPE"

	//party
	C3_HOST_PARTY         = "HOST_PARTY"
	C3_JOIN_PARTY         = "JOIN_PARTY"
	C3_REFRESH_PARTY_ITEM = "REFRESH_PARTY_ITEM"
	C3_MARK_PARTY_ITEM    = "MARK_PARTY_ITEM"
	C3_HOST_PARTY_JOIN    = "HOST_PARTY_JOIN"

	C3_PK_DESTROY = "PK_DESTROY"
)
const (
	KOR_CODE_ONCE = "주의 사항 본 쿠폰은 계정당 1회만 사용 가능합니다"

	Kor_CODE_TITLE     = "중학교 챕터 클리어 보상 - 에브리타운"
	KOR_CODE_ATTENTION = "유나의 옷장 스웨터 공방"
	KOR_CODE_EXP       = "본 쿠폰은 2017년 12월 31일까지만 사용 가능합니다"
	KOR_CODE_FROM      = "본 쿠폰은 에브리타운에서만 사용이 가능합니다"

	Kor_CODE_TITLE2     = "중학교 챕터 클리어 보상 - 바이킹아일랜드"
	KOR_CODE_ATTENTION2 = "흑진주 50개"
	KOR_CODE_EXP2       = "본 쿠폰은 2017년 12월 31일까지만 사용 가능합니다"
	KOR_CODE_FROM2      = "본 쿠폰은 바이킹아일랜드에서만 사용이 가능합니다"

	Kor_CODE_TITLE3     = "중학교 챕터 클리어 보상 - 두근두근레스토랑"
	KOR_CODE_ATTENTION3 = "루비 30개"
	KOR_CODE_EXP3       = "본 쿠폰은 2017년 12월 31일까지만 사용 가능합니다"
	KOR_CODE_FROM3      = "본 쿠폰은 두근두근레스토랑에서만 사용이 가능합니다"
)
const (
	Kor_GAMECBT_TITLE   = "CBT 사전예약 참여보상"
	Kor_GAMECBT_CONTENT = "유나의옷장 CBT 사전예약 참여 보상입니다.CBT에 참여해주셔서 감사드립니다. "

	Kor_NORMAL_PLAYER_TITLE   = "사전예약 보상"
	Kor_NORMAL_PLAYER_CONTENT = "유나의옷장 사전예약 보상입니다. 사전예약에 참여해주셔서 감사드립니다."

	Kor_NORMAL_INVITE_TITLE   = "사전예약 친구초대 보상"
	Kor_NORMAL_INVITE_CONTENT = "유나의옷장 사전예약 친구초대 보상입니다."
)
const (
	SRC_PAY             = "PAY"
	SRC_PK              = "PK"
	SRC_PK_BOUNS        = "PKBOUNS"
	SRC_MISSION         = "MISSION"
	SRC_TASK            = "TASK"
	SRC_MAIL            = "MAIL"
	SRC_DESIGNER_PURSE  = "DESIGNER_PURSE"
	SRC_SHOP            = "SHOP"
	SRC_OFFICIAL_SHOP   = "OFFICIAL_SHOP"
	SRC_PAPER_TRADE     = "PAPER_TRADE"
	SRC_JOIN_ADVERISING = "JOIN_ADVERISING"

	SRC_DIAMOND_CONSUME        = "DIAMOND_CONSUME"
	SRC_UNLOCK_MISSION         = "UNLOCK_MISSION"
	SRC_SWITCH_LINE            = "SWITCH_LINE"
	SRC_S_SUIT                 = "S_SUIT"
	SRC_COSPLAY_ITEM           = "COSPLAY_ITEM"
	SRC_TAG                    = "TAG"
	SRC_LOTTERY                = "LOTTERY"
	SRC_BUY_TILI               = "BUY_TILI"
	SRC_BUY_ITEM               = "BUY_ITEM"
	SRC_SHARE                  = "SHARE"
	SRC_ENDING                 = "ENDING"
	SRC_MAGIC                  = "MAGIC"
	SRC_CLO_PIECE_SWAP_REQUEST = "CLO_PIECE_SWAP_REQUEST"
	SRC_CLO_PIECE_SWAP         = "CLO_PIECE_SWAP"
	SRC_SELL_CLOTHES           = "SELL_CLOTHES"
	SRC_MAGIC_SPEED            = "MAGIC_SPEED"
	SRC_COMBINE                = "COMBINE"
	SRC_EVENT                  = "EVENT"
	SRC_DECOMPOSE              = "DECOMPOSE"
	SRC_ADD_PARTY              = "ADD_PARTY"
	SRC_JOIN_PARTY             = "JOIN_PARTY"
	SRC_MARK_PARTY_ITEM        = "MARK_PARTY_ITEM"
	SRC_GIFT_PACK              = "GIFT_PACK"
	SRC_UP_CUSTOM              = "UP_CUSTOM"
	SRC_DOWN_CUSTOM            = "DOWN_CUSTOM"
	SRC_BUY_BACK_PK_CLO        = "BUY_BACK_PK_CLO"
	SRC_THEATER                = "THEATER"
	SRC_TINY_PACK              = "TINY_PACK"
	SRC_INVITE_PLAYER          = "INVITE_PLAYER"
	SRC_MONTH_CARD             = "MONTH_CARD"
	SRC_SCRIPT                 = "SCRIPT"
	SRC_FORCE_MONTH_SIGN       = "FORCE_MONTH_SIGN"
	SRC_HOPE                   = "HOPE"
	SRC_IAP_RETURN             = "IAP_RETURN"
	SRC_ONE_DAY                = "ONE_DAY"
	SRC_BOARD                  = "BOARD"
	SRC_REPLY_PARTY            = "REPLY_PARTY"
	SRC_INVITE_PARTY           = "INVITE_PARTY"
	SRC_HELP_HOPE              = "HELP_HOPE"
	SRC_JOIN_PARTY_PARTNER     = "JOIN_PARTY_PARTNER"
	SRC_PARTY_SEND_FLOWER      = "PARTY_SEND_FLOWER"
	SRC_INVITE_PARTY_PARTNER   = "INVITE_PARTY_PARTNER"
	SRC_TAILOR                 = "TAILOR"
	SRC_DYE                    = "DYE"
	SRC_CREATE_GUILD           = "CREATE_GUILD"
	SRC_GUILD_SHARE            = "GUILD_SHARE"
	SRC_GUILD_WAR              = "GUILD_WAR"
	SRC_REPLAY_MISSION         = "REPLAY_MISSION"
	SRC_CHANGE_STAMP           = "CHANGE_STAMP"
	SRC_BUY_SPECIAL_MISSION    = "BUY_SPECIAL_MISSION"
	SRC_SUIT_REWARD            = "SUIT_REWARD"
	SRC_KOR_INVITE             = "KOR_INVITE"
	SRC_INVITE_KOR             = "INVITE_KOR"
	SRC_FIRST_PLAY             = "FIRST_PLAY"
	SRC_BUY_BACKGROUND         = "BUY_BACKGROUND"
	SRC_BUY_THEATER            = "BUY_THEATER"
	SRC_RT_PARTY_REWARD        = "RT_PARTY_REWARD"

	//PIXIE
	SRC_PAPER_COPY_REPORT  = "PAPER_COPY_REPORT"
	SRC_DRAW_DTREET_WALLET = "DRAW_STREET_WALLET"

	SRC_BUY_DESIGN_COIN_PRICE_TOKEN = "BUY_DESIGN_COIN_PRICE_TOKEN"
)
